### ISSUE TITLE
Demo does not load in EDGE at all

### ISSUE THREAD

**Issue by venkatpolisetti** [svitkin/leaflet-timeline-slider#2] opened 2019-10-11 18:13 UTC
Hi,

Great plugin.

EDGE does not support Spread operator for object literals. Line 105 which is:

            allChangeMapParameters = {...mapParams, ...that.options.extraChangeMapParams};

Thanks,
Venkat

**Comment by venkatpolisetti** [comment] 2019-10-11 18:38
Changing the above line with below at least loaded the map and slider but slider css needs fixing I guess for EDGE. It is not displaying the slider bar to begin with and will only display as you start clicking on the intervals.
         
   allChangeMapParameters = Object.assign({}, mapParams, that.options.extraChangeMapParams);

**Comment by svitkin** [comment] 2019-10-11 22:24
Thanks for pointing this out. I will take a look as soon as I can and try to adapt the styles for edge as well.

**Comment by venkatpolisetti** [comment] 2019-10-11 22:34
@svitkin Thank you for your quick response. I want to use your plugin on my leaflet map and hoping the styles would be fixed soon. Here is link to cssportal that has good styles for input range that works on all browsers including edge. I have actually loaded that website in EDGE and see them working and thought you may be interested in it.

https://www.cssportal.com/style-input-range/

Also a JSFiddle by some one who did fix the styles for EDGE:

http://jsfiddle.net/brenna/f4uq9edL/?utm_source=website&utm_medium=embed&utm_campaign=f4uq9edL

**Comment by svitkin** [comment] 2019-10-25 03:36
Hey @venkatpolisetti sorry it has taken me a while to get back to this. Currently developing on a mac os, and the only version of Edge I could find for a mac os is the chromium based one Microsoft currently has in beta, which of course won't reproduce the issue. I'm going to try to find my way to a windows machine soon to reproduce the issue and try to get a fix in. In the meantime, feel free to put in a pull request if you have a fix.

**Comment by svitkin** [comment] 2020-12-10 17:44
Closing this for now because the plugin works with new Edge Chromium.

**Closed by svitkin** 2020-12-10 17:44 UTC
